name: Minecraft 3-Min Auto Start

on:
  schedule:
    - cron: '*/30 * * * *'
  workflow_dispatch:

jobs:
  keep-alive:
    runs-on: ubuntu-latest
    steps:
      - name: Auto Check Loop
        run: |
          for i in {1..10}
          do
            echo "Тексеру №$i..."
            
            STATUS_RES=$(curl -s -X GET "https://panel.cloudblaze.org/api/client/servers/d5d42242/resources" \
            -H "Authorization: Bearer ${{ secrets.MC_API_KEY }}" \
            -H "Accept: application/json")
            
            if [[ "$STATUS_RES" == *"offline"* ]]; then
              echo "Сервер өшіп тұр! Қосылуда..."
              curl -s -X POST "https://panel.cloudblaze.org/api/client/servers/d5d42242/power" \
              -H "Authorization: Bearer ${{ secrets.MC_API_KEY }}" \
              -H "Content-Type: application/json" \
              -d '{"signal": "start"}'
            else
              echo "Сервер жұмыс істеп тұр немесе қосылуда."
            fi

            if [ $i -lt 10 ]; then
              echo "3 минут күту..."
              sleep 180
            fi
          done
